"""Prediction-market pipeline: parsing, pricing, gating, fills and settlement."""

from __future__ import annotations

import math

import pytest

from flowbot.core.config import PolymarketConfig
from flowbot.core.types import BookLevel, BookSnapshot
from flowbot.polymarket.client import PolymarketClient, infer_resolution, parse_market
from flowbot.polymarket.engine import PolymarketPipeline
from flowbot.polymarket.market import Outcome, PredictionMarket, ResolutionSpec, parse_iso
from flowbot.polymarket.pricing import (
    assess, brier_score, calibration_report, gbm_probability, kelly_fraction,
    model_probability, norm_cdf, reliability_table,
)

# A real 15-minute BTC window, shape taken from the live Gamma API
# (btc-updown-15m-1789938900, checked 2026-09-20): TWAP-vs-window-open
# settlement, no dollar figure anywhere in the text, and the market opened
# for trading nearly a day before its own comparison window starts.
TWAP_RAW = {
    "id": "4738964",
    "slug": "btc-updown-15m-1789938900",
    "question": "Bitcoin Up or Down - September 20, 5:15PM-5:30PM ET",
    "conditionId": "0xdeadbeef",
    "clobTokenIds": '["111","222"]',
    "outcomes": '["Up","Down"]',
    "outcomePrices": '["0.505","0.495"]',
    "resolutionSource": "https://data.chain.link/streams/btc-usd-twap-60s-streams",
    "startDate": "2026-09-19T21:54:17.482622Z",       # market opened for trading
    "eventStartTime": "2026-09-20T21:15:00Z",          # the window itself
    "endDate": "2026-09-20T21:30:00Z",
    "orderPriceMinTickSize": 0.01,
    "orderMinSize": 5,
    "description": (
        "This market will resolve to \"Up\" if the time-weighted average price "
        "(TWAP) of Bitcoin, generated by Chainlink, of the time range specified "
        "in the title is greater than or equal to the price at the beginning of "
        "that range. Otherwise, it will resolve to \"Down\"."
    ),
    "cryptoMarketConfigId": "btc-15m-twap-60",
    "cryptoMarketConfig": {
        "id": "btc-15m-twap-60", "asset": "btc", "duration": "15m",
        "twapEnabled": True, "twapLookbackSeconds": 60,
    },
}

RAW = {
    "id": "512",
    "slug": "bitcoin-up-or-down-july-4",
    "question": "Bitcoin Up or Down on July 4?",
    "conditionId": "0xabc",
    "clobTokenIds": '["111","222"]',
    "outcomes": '["Up","Down"]',
    "outcomePrices": '["0.53","0.47"]',
    "endDate": "2026-07-05T16:00:00Z",
    "startDate": "2026-07-04T16:00:00Z",
    "volumeNum": 128000,
    "liquidityNum": 42000,
    "orderPriceMinTickSize": 0.01,
    "description": ("This market resolves Up if the Binance 1 minute candle close for "
                    "BTCUSDT at 12:00 PM ET on July 5 is above $62,500."),
}


def market_fixture(**kw) -> PredictionMarket:
    m = PredictionMarket(
        id="9", slug="bitcoin-up-or-down-today", question="q", condition_id="c",
        outcomes=[Outcome("Up", "t1"), Outcome("Down", "t2")],
        end_ts=6 * 3_600_000, tick_size=0.01, min_order_size=5,
    )
    m.resolution = ResolutionSpec(
        reference="binance:BTCUSDT:1m-close", strike=64_000, strike_known=True
    )
    for k, v in kw.items():
        setattr(m, k, v)
    return m


def books(yes_ask=0.51, no_ask=0.50, size=600):
    yes = BookSnapshot(0, [BookLevel(yes_ask - 0.02, size)],
                       [BookLevel(yes_ask, size), BookLevel(yes_ask + 0.02, size * 2)])
    no = BookSnapshot(0, [BookLevel(no_ask - 0.03, size)], [BookLevel(no_ask, size)])
    return yes, no


# ------------------------------------------------------------------ parsing

def test_market_parsing_pulls_tokens_and_dates():
    m = parse_market(RAW)
    assert m.slug == "bitcoin-up-or-down-july-4"
    assert m.yes.name == "Up" and m.yes.token_id == "111"
    assert m.no.token_id == "222"
    assert m.end_ts == parse_iso("2026-07-05T16:00:00Z")
    assert m.volume == 128000


def test_resolution_inference_finds_source_strike_and_timezone():
    spec = infer_resolution(RAW)
    assert spec.reference == "binance:BTCUSDT:1m-close"
    assert spec.strike == 62_500 and spec.strike_known
    assert "Eastern" in spec.timezone_note
    assert spec.verified


def test_unparseable_resolution_is_not_verified():
    spec = infer_resolution({"description": "Resolves according to the vibes."})
    assert spec.reference == "unknown"
    assert not spec.verified


def test_twap_window_resolution_has_no_strike_until_the_engine_fills_it_in():
    spec = infer_resolution(TWAP_RAW)
    assert spec.reference == "chainlink:BTC-USD:twap60s-vs-window-open"
    assert spec.strike_mode == "window_open"
    # No "$X" figure exists in this family's text - the regex must not fire
    # and invent a strike for it.
    assert not spec.strike_known
    assert not spec.verified          # correctly refuses to trade, for now


def test_window_open_ts_is_the_comparison_window_not_the_listing_date():
    m = parse_market(TWAP_RAW)
    # startDate is when the market opened for trading (almost a day earlier);
    # eventStartTime is the actual 15-minute window this market is about.
    assert m.start_ts == parse_iso("2026-09-19T21:54:17.482622Z")
    assert m.window_open_ts == parse_iso("2026-09-20T21:15:00Z")
    assert m.window_open_ts != m.start_ts


# -------------------------------------------------------------------- client

async def test_search_markets_never_sends_slug_as_a_server_filter():
    # Gamma's `slug` query param is an exact match - sending a family prefix
    # there (the old behaviour) silently returns [] every time, on every
    # family. Regression: assert the param is simply never sent.
    import httpx

    seen = {}

    def handler(request: httpx.Request) -> httpx.Response:
        seen["params"] = dict(request.url.params)
        return httpx.Response(200, json=[RAW])

    client = PolymarketClient()
    client._client = httpx.AsyncClient(transport=httpx.MockTransport(handler))
    markets = await client.search_markets("bitcoin-up-or-down")
    assert "slug" not in seen["params"]
    assert markets and markets[0].slug == RAW["slug"]        # client-side filter still works


async def test_get_market_by_slug_sends_an_exact_slug_and_parses_the_hit():
    import httpx

    seen = {}

    def handler(request: httpx.Request) -> httpx.Response:
        seen["params"] = dict(request.url.params)
        return httpx.Response(200, json=[TWAP_RAW])

    client = PolymarketClient()
    client._client = httpx.AsyncClient(transport=httpx.MockTransport(handler))
    market = await client.get_market_by_slug("btc-updown-15m-1789938900")
    assert seen["params"] == {"slug": "btc-updown-15m-1789938900"}
    assert market is not None and market.slug == TWAP_RAW["slug"]


async def test_get_market_by_slug_returns_none_when_nothing_matches():
    import httpx

    client = PolymarketClient()
    client._client = httpx.AsyncClient(
        transport=httpx.MockTransport(lambda r: httpx.Response(200, json=[]))
    )
    assert await client.get_market_by_slug("btc-updown-15m-0") is None


# ------------------------------------------------------------------ pricing

def test_norm_cdf_and_gbm_sanity():
    assert norm_cdf(0) == pytest.approx(0.5)
    assert gbm_probability(100, 100, 0.5, 0) == 0.0            # expired, not above
    assert gbm_probability(101, 100, 0.5, 0) == 1.0
    # At the money with a long horizon the drag pulls it just under a half.
    p = gbm_probability(100, 100, 0.5, 86400 * 30)
    assert 0.4 < p < 0.5


def test_in_the_money_probability_rises_as_time_runs_out():
    far = gbm_probability(64_800, 64_000, 0.55, 86_400)
    near = gbm_probability(64_800, 64_000, 0.55, 600)
    assert near > far > 0.5


def test_momentum_tilt_moves_the_probability_the_right_way_but_only_a_little():
    flat, _ = model_probability(64_000, 64_000, 0.55, 3_600, score=0.0)
    bull, info = model_probability(64_000, 64_000, 0.55, 3_600, score=0.9)
    bear, _ = model_probability(64_000, 64_000, 0.55, 3_600, score=-0.9)
    assert bull > flat > bear
    # The honest result: over an hour the tilt is worth a fraction of a point,
    # which is the whole reason the pipeline hunts stale quotes instead.
    assert abs(info["tilt_contribution"]) < 0.01


def test_probability_never_claims_certainty():
    p, _ = model_probability(90_000, 64_000, 0.55, 60, score=1.0)
    assert p <= 0.98


def test_vol_haircut_pulls_probability_toward_a_coin_flip():
    sharp, _ = model_probability(64_800, 64_000, 0.55, 86_400, vol_haircut=1.0)
    hedged, _ = model_probability(64_800, 64_000, 0.55, 86_400, vol_haircut=1.5)
    assert 0.5 < hedged < sharp


def test_kelly_fraction_math():
    assert kelly_fraction(0.6, 0.5) == pytest.approx(0.2)
    assert kelly_fraction(0.5, 0.5) == 0.0
    assert kelly_fraction(0.4, 0.5) == 0.0                     # never bet a negative edge
    assert kelly_fraction(0.9, 0.1) == pytest.approx(0.888, abs=0.001)


# -------------------------------------------------------------------- edges

def test_stale_quote_against_a_moved_spot_is_the_edge():
    m = market_fixture()
    yes, no = books(yes_ask=0.51)
    p, _ = model_probability(64_800, 64_000, 0.55, 6 * 3600, score=0.6)
    a = assess(m, yes, no, p, equity=10_000, now_ms=0)
    assert a.side == "yes"
    assert a.edge > 0.15
    assert a.tradable
    assert a.shares >= m.min_order_size
    assert a.stake <= 10_000 * 0.02 + 1e-6                     # stake cap honoured


def test_fair_quote_produces_no_trade():
    m = market_fixture()
    p, _ = model_probability(64_000, 64_000, 0.55, 6 * 3600, score=0.1)
    yes, no = books(yes_ask=round(p, 2), no_ask=round(1 - p, 2))
    a = assess(m, yes, no, p, equity=10_000, now_ms=0)
    assert not a.tradable
    assert any("edge" in b for b in a.blockers)


def test_unverified_resolution_blocks_the_trade():
    m = market_fixture()
    m.resolution = ResolutionSpec()                            # unknown rule
    yes, no = books(yes_ask=0.30)
    a = assess(m, yes, no, 0.80, equity=10_000, now_ms=0)
    assert not a.tradable
    assert any("resolution rule" in b for b in a.blockers)


def test_imminent_resolution_blocks_the_trade():
    m = market_fixture(end_ts=60_000)
    yes, no = books(yes_ask=0.30)
    a = assess(m, yes, no, 0.80, equity=10_000, now_ms=0, min_seconds=300)
    assert any("resolution" in b for b in a.blockers)


def test_wide_spread_blocks_the_trade():
    m = market_fixture()
    yes = BookSnapshot(0, [BookLevel(0.30, 500)], [BookLevel(0.45, 500)])
    no = BookSnapshot(0, [BookLevel(0.40, 500)], [BookLevel(0.60, 500)])
    a = assess(m, yes, no, 0.80, equity=10_000, now_ms=0, max_spread=0.04)
    assert any("spread" in b for b in a.blockers)


def test_edge_is_measured_against_the_ask_not_the_mid():
    m = market_fixture()
    yes, no = books(yes_ask=0.60)
    a = assess(m, yes, no, 0.63, equity=10_000, now_ms=0, min_edge=0.01)
    # mid is 0.59, ask is 0.60, and we add a tick of slippage: cost 0.61.
    assert a.cost == pytest.approx(0.61)
    assert a.edge == pytest.approx(0.02)


def test_lot_minimum_shares_can_still_miss_the_venues_minimum_order_value():
    # Regression, found live against Polymarket: a market with a 0.12 ask and
    # a 5-share lot minimum sizes 5 shares = $0.60, which the lot-size check
    # alone waves through but the real venue rejects (min order value $1).
    m = market_fixture(min_order_size=5, min_notional=1.0)
    yes, no = books(yes_ask=0.12, no_ask=0.86, size=600)
    a = assess(m, yes, no, model_p=0.30, equity=10_000, now_ms=0, min_edge=0.01)
    assert a.side == "yes" and a.cost == pytest.approx(0.13)
    # Rounded up to the smallest lot multiple that clears $1, not left at 5.
    assert a.shares * a.cost >= 1.0
    assert a.shares % m.min_order_size == 0
    assert a.tradable


def test_size_is_capped_by_the_book():
    m = market_fixture()
    yes, no = books(yes_ask=0.30, size=20)
    a = assess(m, yes, no, 0.80, equity=1_000_000, now_ms=0)
    assert a.shares <= 10                                       # half of 20 resting


# --------------------------------------------------------- window discovery

async def test_discover_windows_computes_the_slug_instead_of_searching():
    # The epoch in btc-updown-15m-<epoch> is the window's own open time,
    # aligned to window_seconds. 1789938900 % 900 == 0 (a real example).
    pipe = PolymarketPipeline(PolymarketConfig(window_seconds=900), equity=10_000)
    requested = []

    async def fake(slug):
        requested.append(slug)
        return market_fixture(id=slug, slug=slug) if slug.endswith("900") else None

    pipe.client.get_market_by_slug = fake
    now_ms = 1789938900_000 + 37_000     # 37s into the window
    out = await pipe._discover_windows(now_ms)

    assert requested == ["btc-updown-15m-1789938900", "btc-updown-15m-1789939800"]
    assert len(out) == 1                 # only the current window resolved
    assert out[0].slug == "btc-updown-15m-1789938900"


# ------------------------------------------------------------- strike fill-in

def test_resolve_strike_waits_for_the_window_to_actually_open():
    pipe = PolymarketPipeline(PolymarketConfig(), equity=10_000)
    pipe.bind(lambda: (0.0, 0.5), lambda: 0.0, window_open_provider=lambda ts: 81_000.0)
    m = market_fixture()
    m.resolution = ResolutionSpec(
        reference="chainlink:BTC-USD:twap60s-vs-window-open", strike_mode="window_open",
    )
    m.window_open_ts = 10_000

    pipe._resolve_strike(m, now_ms=5_000)            # window hasn't opened yet
    assert not m.resolution.strike_known

    pipe._resolve_strike(m, now_ms=10_500)           # now it has
    assert m.resolution.strike_known
    assert m.resolution.strike == 81_000.0
    assert m.resolution.verified


def test_resolve_strike_is_a_noop_without_a_provider_or_once_already_known():
    pipe = PolymarketPipeline(PolymarketConfig(), equity=10_000)   # never bound
    m = market_fixture()
    m.resolution = ResolutionSpec(strike_mode="window_open")
    m.window_open_ts = 0
    pipe._resolve_strike(m, now_ms=1_000)
    assert not m.resolution.strike_known                 # no provider - stays unknown


# --------------------------------------------------------------- forced mode

def test_force_if_due_takes_the_best_side_at_the_venue_minimum():
    cfg = PolymarketConfig(force_min_trades=True, min_edge=0.5,
                            force_trade_before_close_s=120, min_seconds_to_resolution=60)
    pipe = PolymarketPipeline(cfg, equity=10_000)
    m = market_fixture()
    a = assess(m, *books(yes_ask=0.50, no_ask=0.50), model_p=0.50,
               equity=10_000, now_ms=0, min_edge=cfg.min_edge)
    a.seconds_left = 90                  # inside the force window, above the floor
    assert not a.tradable                # organic gate correctly refused it

    assert pipe._force_if_due(m, a) is True
    assert a.tradable
    assert a.shares == m.min_order_size
    assert a.kelly_fraction == 0.0
    assert all(b.startswith("forced:") for b in a.blockers)


def test_force_if_due_sizes_past_the_venues_minimum_order_value_too():
    cfg = PolymarketConfig(force_min_trades=True, min_edge=0.5,
                            force_trade_before_close_s=120, min_seconds_to_resolution=60)
    pipe = PolymarketPipeline(cfg, equity=10_000)
    m = market_fixture(min_order_size=5, min_notional=1.0)
    yes, no = books(yes_ask=0.12, no_ask=0.86, size=600)
    a = assess(m, yes, no, model_p=0.14, equity=10_000, now_ms=0, min_edge=cfg.min_edge)
    a.seconds_left = 90
    assert pipe._force_if_due(m, a) is True
    assert a.shares * a.cost >= m.min_notional
    assert a.shares % m.min_order_size == 0


def test_force_if_due_still_refuses_an_unverified_market():
    cfg = PolymarketConfig(force_min_trades=True, force_trade_before_close_s=120,
                            min_seconds_to_resolution=60)
    pipe = PolymarketPipeline(cfg, equity=10_000)
    m = market_fixture()
    m.resolution = ResolutionSpec()                       # unknown rule
    a = assess(m, *books(), model_p=0.5, equity=10_000, now_ms=0)
    a.seconds_left = 90
    assert pipe._force_if_due(m, a) is False               # can't score it either way


def test_force_if_due_respects_the_timing_window():
    cfg = PolymarketConfig(force_min_trades=True, min_edge=0.5,
                            force_trade_before_close_s=120, min_seconds_to_resolution=60)
    pipe = PolymarketPipeline(cfg, equity=10_000)
    m = market_fixture()
    too_early = assess(m, *books(yes_ask=0.5, no_ask=0.5), model_p=0.5,
                        equity=10_000, now_ms=0, min_edge=cfg.min_edge)
    too_early.seconds_left = 300
    assert pipe._force_if_due(m, too_early) is False       # organic still has a chance

    too_late = assess(m, *books(yes_ask=0.5, no_ask=0.5), model_p=0.5,
                       equity=10_000, now_ms=0, min_edge=cfg.min_edge)
    too_late.seconds_left = 30
    assert pipe._force_if_due(m, too_late) is False        # can't even round-trip safely


async def test_forced_trade_fires_end_to_end_and_stays_out_of_calibration(monkeypatch):
    from flowbot.polymarket import engine as engine_mod

    cfg = PolymarketConfig(
        force_min_trades=True, min_edge=0.5,               # organic edge unreachable
        force_trade_before_close_s=600, min_seconds_to_resolution=60,
    )
    pipe = PolymarketPipeline(cfg, equity=10_000)
    pipe.latency_ms = 1
    pipe.bind(lambda: (64_000.0, 0.55), lambda: 0.0)

    fixed_now = 0
    monkeypatch.setattr(engine_mod.time, "time", lambda: fixed_now / 1000.0)

    m = market_fixture(end_ts=300_000)                     # 5 minutes out - inside 600s
    yes, no = books(yes_ask=0.50, no_ask=0.50)

    async def fake_discover(now_ms):
        return [m]

    async def fake_book(token_id):
        return yes if token_id == "t1" else no

    async def no_market(_id):
        return None

    pipe._discover_windows = fake_discover
    pipe.client.get_book = fake_book
    pipe.client.get_market = no_market

    out = await pipe.poll()
    assert len(out) == 1 and out[0].blockers[0].startswith("forced:")
    assert len(pipe.positions) == 1
    pos = pipe.positions[0]
    assert pos.forced and pos.shares == m.min_order_size

    # Settle it and confirm it never reaches the calibration set.
    fixed_now = 300_001
    await pipe._settle_due(fixed_now)
    assert pos.settled
    assert pipe.forecasts == []
    state = pipe.state()
    assert state["forced_stats"]["settled"] == 1
    assert state["calibration"] is None


# ------------------------------------------------------------------ pipeline

async def test_pipeline_fills_when_the_quote_survives_the_round_trip():
    pipe = PolymarketPipeline(PolymarketConfig(), equity=10_000)
    pipe.latency_ms = 1
    pipe.bind(lambda: (64_800.0, 0.55), lambda: 0.6)
    m = market_fixture()
    yes, no = books(yes_ask=0.51)
    p, _ = model_probability(64_800, 64_000, 0.55, 6 * 3600, score=0.6)
    a = assess(m, yes, no, p, 10_000, 0)

    async def still_there(_token):
        return yes

    pipe.client.get_book = still_there
    pos = await pipe._paper_buy(m, a, "t1", 0)
    assert pos is not None
    assert pos.shares > 0
    assert pos.cost == pytest.approx(0.51)
    assert pipe.equity == pytest.approx(10_000 - pos.stake)


async def test_pipeline_misses_when_the_quote_is_pulled():
    pipe = PolymarketPipeline(PolymarketConfig(), equity=10_000)
    pipe.latency_ms = 1
    m = market_fixture()
    yes, no = books(yes_ask=0.51)
    a = assess(m, yes, no, 0.77, 10_000, 0)

    async def repriced(_token):
        return BookSnapshot(0, [BookLevel(0.70, 500)], [BookLevel(0.80, 500)])

    pipe.client.get_book = repriced
    assert await pipe._paper_buy(m, a, "t1", 0) is None
    assert pipe.equity == 10_000
    assert "no fill" in pipe.events[-1]["message"]


async def test_settlement_pays_one_dollar_a_share_and_records_calibration():
    pipe = PolymarketPipeline(PolymarketConfig(), equity=10_000)
    pipe.latency_ms = 1
    pipe.bind(lambda: (64_800.0, 0.55), lambda: 0.6)
    m = market_fixture(end_ts=0)
    yes, _no = books(yes_ask=0.51)
    a = assess(market_fixture(), yes, _no, 0.77, 10_000, 0)

    async def still_there(_token):
        return yes

    async def no_market(_id):
        return None

    pipe.client.get_book = still_there
    pipe.client.get_market = no_market
    pos = await pipe._paper_buy(m, a, "t1", 0)
    await pipe._settle_due(1)

    assert pos.settled and pos.outcome == 1
    assert pos.pnl == pytest.approx(pos.shares * (1 - pos.cost))
    assert pipe.equity == pytest.approx(10_000 + pos.pnl)
    assert pipe.forecasts and pipe.forecasts[0][1] == 1
    state = pipe.state()
    assert state["stats"]["wins"] == 1
    assert state["calibration"]["n"] == 1


async def test_losing_settlement_costs_the_stake():
    pipe = PolymarketPipeline(PolymarketConfig(), equity=10_000)
    pipe.latency_ms = 1
    pipe.bind(lambda: (63_000.0, 0.55), lambda: -0.6)      # BTC below the strike
    m = market_fixture(end_ts=0)
    yes, no = books(yes_ask=0.51)
    a = assess(market_fixture(), yes, no, 0.77, 10_000, 0)

    async def still_there(_token):
        return yes

    async def no_market(_id):
        return None

    pipe.client.get_book = still_there
    pipe.client.get_market = no_market
    pos = await pipe._paper_buy(m, a, "t1", 0)
    await pipe._settle_due(1)
    assert pos.outcome == 0
    assert pos.pnl == pytest.approx(-pos.stake)
    assert pipe.equity == pytest.approx(10_000 - pos.stake)


# --------------------------------------------------------------- calibration

def test_brier_and_skill():
    perfect = [(1.0, 1), (0.0, 0)]
    assert brier_score(perfect) == 0.0
    coin = [(0.5, 1), (0.5, 0)]
    assert brier_score(coin) == pytest.approx(0.25)
    report = calibration_report([(0.6, 1)] * 60 + [(0.6, 0)] * 40)
    assert report["n"] == 100
    assert report["base_rate"] == pytest.approx(0.6)


def test_reliability_table_buckets_forecasts():
    table = reliability_table([(0.65, 1)] * 70 + [(0.65, 0)] * 30, bins=10)
    row = [r for r in table if r["n"]][0]
    assert row["forecast"] == pytest.approx(0.65)
    assert row["observed"] == pytest.approx(0.70)
    assert row["gap"] == pytest.approx(0.05)


def test_overconfident_model_shows_a_negative_gap():
    table = reliability_table([(0.9, 1)] * 50 + [(0.9, 0)] * 50, bins=10)
    row = [r for r in table if r["n"]][0]
    assert row["gap"] < -0.3          # says 90%, happens 50% of the time
